config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get "up", to: "rails/health#show", as: :rails_health_check
  get "how_to_use", to: "pages#how_to_use", as: :how_to_use

  resources :posts do
    collection do
      get :search
      get :bookmarks
    end

    resources :comments, only: [ :create, :destroy, :edit, :update ]
    resources :bookmarks, only: [ :create, :destroy ]
  end

  resource :profile, only: [ :edit, :update, :show ]

  get "mountain", to: "mountain#search"

  get "search_routes", to: "routes#search"
  get "routes/show"

  get "train_route_sidebar", to: "train_routes#sidebar"

  get "facilities", to: "facilities#search"

  root to: "home#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [ :create, :destroy, :edit, :update ]
  before_action :set_comment, only: [ :destroy, :edit, :update ]

  def edit
    @editing_comment = @post.comments.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    render "posts/show"
  end

  def update
    unless @comment.user == current_user
      redirect_to @post, alert: "他人のコメントは編集できません"
      return
    end

    if @comment.update(comment_params)
      redirect_to @post, notice: "コメントを更新しました"
    else
      render :edit
    end
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: "コメントを投稿しました"
    else
      redirect_to @post, alert: "エラーが発生しました"
    end
  end

  def destroy
    Rails.logger.debug "Deleting comment with ID: #{params[:id]}"
    if @comment.user == current_user && @comment.destroy
      redirect_to @post, notice: "コメントを削除しました"
    else
      redirect_to @post, alert: "エラーが発生しました"
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- app/views/comments/_comment.html.erb -->

<div class="p-2 mb-3 border rounded">
  <p><strong><%= comment.user.name %></strong>：<%= comment.body %></p>

  <% if comment.user == current_user %>
    <%= link_to '編集', edit_post_comment_path(comment.post, comment), class: "text-blue-500 mr-2" %>

    <%= link_to '削除', post_comment_path(comment.post, comment),
                data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' },
                class: "text-red-500" %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], local: true) do |f| %>
  <div class="mb-2">
    <%= f.label :body, "コメント内容" %><br>
    <%= f.text_area :body, rows: 3, class: "w-80 p-2 border rounded" %>
  </div>

  <%= f.submit comment.persisted? ? "更新する" : "投稿する", class: "bg-blue-600 text-white rounded px-3 py-1" %>
<% end %>

app/views/comments/edit.html.erb
<h2 class="text-xl font-bold mb-4">コメントを編集</h2>

<%= render 'comments/form', post: @post, comment: @comment %>

<%= link_to "戻る", post_path(@post), class: "text-blue-600 underline mt-4 block" %>